let chatHistory = [
    { role: "system", content: "You are a helpful assistant specializing in Ifa divination and Yoruba spirituality." }
];

const ifaKnowledgeBase = {
    "hello": "Hello! How can I assist you today?",
    "hi": "Hi there! What would you like to know?",
    "good morning": "Good morning! May your day be filled with blessings.",
    "good afternoon": "Good afternoon! How may I help you?",
    "good evening": "Good evening! I’m here to answer your questions.",
    "how are you": "I’m just a bot, but I’m always here to help!",
    "thank you": "You’re welcome! Let me know if you have more questions.",
    "thanks": "You're welcome! If you need more guidance, feel free to ask.",
    "collaboration": "<p>For collaboration kindly reach us on Whatsapp <a style='color:green;' target='_blank' aria-label='Chat on WhatsApp' href='https://wa.me/2348034256265'> +2348034256265<a/>. Ire o.</p> ",
    "collaborate": "<p>For collaboration kindly reach us on Whatsapp <a style='color:green;' target='_blank' aria-label='Chat on WhatsApp' href='https://wa.me/2348034256265'> +2348034256265<a/>. Ire o.</p> ",


    
    
    "ajagunmale": "Ajagunmale refers to the Chief Priest (Oluwo) or head of celestial beings in heavern (Orun) who serve Olodumare and maintain cosmic order.",
    "ayewo": "Consultation is a spiritual process in which a trained diviner (Babalawo) communicates with the divine to provide guidance. Done using sacred tools such as the Opele chain or palm nuts to reveal messages from the Odu Ifa. Before an Ifa consultation, you should have a clear mind, be open to guidance, and approach the process with sincerity.",
    "awonomaja": "Awonomaja refers to the Chief Priest (Oluwo) or head of celestial beings on earth (Aye) who serve Olodumare and maintain cosmic order.",
    "babalawo": "A Babalawo is a high priest of Ifa who is trained in divination, ritual work, and spiritual guidance.",
    "consult": "Anyone seeking guidance, whether Yoruba or not, can consult Ifa for wisdom and direction.",
    "consultation": "Consultation is a spiritual process in which a trained diviner (Babalawo) communicates with the divine to provide guidance. Done using sacred tools such as the Opele chain or palm nuts to reveal messages from the Odu Ifa. Before an Ifa consultation, you should have a clear mind, be open to guidance, and approach the process with sincerity.",
    "charms": "Charms are spiritual objects infused with energy to bring protection, luck, or influence events.",
    "cleansing": "Ifa recommends spiritual baths, prayers, and herbs to cleanse one's aura from negative energy.",
    "creation": "At the outset, Heaven (Orun) and Earth (Aye) was created, thereafter, Olodumare looked at his shadow on the ground (ile), commanded the shadow to be by Him, to open his mouth, to speak up, and continue speaking with Him. The shadow stood up as commanded and looked like Olodumare, and the shaow is called Ajagunmale. Olodumare became the King (Olu) in Heaven (Orun) and Ajagunmale became Oluwo (Chief Priest) in Heaven. They spoke together and created Odu and a similar situation happened for Odu, the shadow of Odu is Egan. Therefater, they all decided to create Orunmila (Shadow as Ibo), the other Eboras (Oshooshi/Orishanla, Sango/Oya Oriri, Ogun/Ota gborowo, Oduduwa/Osun Sengese) and Humans (Eniyan (Odu) - 256 in the house of Odu with their corresponding 256 Shadows) and (Eniyan (Egan) - 256 in the house of Egan with their corresponding 256 Shadows). The Humans were sent to Earth (Aye) to dominate. Earth was created on water (omi - olalore), therefore, the earth was shaky and the Humans complained and the Eboras (Ogun, Sango, Obatala, Orunmila) came to make the earth strong with their corresponding tools (Iron, Stones, Sand, Trees and so on.). In no time, Ogun, Sango and Obatala fought over ownership of Aye (earth) and Orunmila sought the invitation of Oduduwa from Heaven to become King (Oba) on Earth (Aye). This was not without hesitation from the three Eboras they were fighting. Earth eventually became peaceful with the wisdom of Orunmila and the emergence of Odu and Egan from Heaven. - Reference is Iwe mimo Olorun Olodumare from Ijo Apapo Odu Cultural Organization.",
    "destiny": "Destiny (Ori) is the divine path chosen before birth. In Ifa, it is believed that one must align with their Ori through wisdom, sacrifice (Ebo), and righteous living (Iwa Pele).",
    "divination": "Divination in Ifa is performed using sacred palm nuts (Ikin Ifa) or the Opele chain to reveal divine messages through Odu Ifa.",
    "dreams": "Dreams (Ala) are messages from the spirit world. Ifa teaches how to interpret dreams to understand hidden meanings.",
    "earth": "The Earth (Aye) is the physical realm where humans live, and it is governed by spirits and ancestors.",
    "ebo": "Ebo is a ritual offering or sacrifice performed to correct spiritual imbalances, remove obstacles, and attract blessings.",
    "eegun": "Egungun represents the spirits of the ancestors. They are honored through rituals and ceremonies for protection, wisdom, and blessings.",
    "egun": "Egungun represents the spirits of the ancestors. They are honored through rituals and ceremonies for protection, wisdom, and blessings.",
    "egungun": "Egungun represents the spirits of the ancestors. They are honored through rituals and ceremonies for protection, wisdom, and blessings.",
    "esu": "Esu is the divine messenger and trickster. He governs communication, crossroads, and choices. Without Esu, no prayers or sacrifices can reach the Orisa.",
    "healing": "Healing in Ifa involves spiritual and physical remedies, including herbs, divination, and offerings to the Orisa.",
    "health": "In Ifa, health (Ilera) is connected to spiritual balance. Illness may be caused by spiritual imbalances and can be treated with rituals, herbs, and prayers.",
    "herbs": "Herbs are for healing, cleansing, and protection.",
    "ifa": "Ifa is the sacred divination system of the Yoruba people, providing wisdom through Odu Ifa. It is the foundation of Yoruba spirituality and philosophy.",
    "incantations": "Incantations (Ofo) are powerful spoken words used in Ifa rituals to invoke spiritual forces.",
    "initiation": "Initiation (Itelodu) is the sacred process of being introduced into Ifa, receiving one's Odu, and learning one's spiritual mission.",
    "isasi": "The evil eye is negative energy or jealousy sent by others. Ifa provides spiritual protection against it.",
    "isefa": "Isefa is the first step in Ifa initiation, where a person receives their first Ifa reading and learns about their spiritual path.",
    "isese": "Isese refers to the traditional religious and cultural practices of the Yoruba people. It represents the worship of Olodumare and reverence for ancestors.",
    "itefa": "Itefa is the full initiation into Ifa, where an individual learns their Odu Ifa and becomes deeply connected with Ifa wisdom.",
    "iwure": "Iwure is a prayer or blessing in Ifa, invoking divine favor and positive energy.",
    "iyanifa": "Iyanifa is a female Ifa priest, trained in divination, spiritual guidance, and healing.",
    "justice": "Justice (Ododo) is sacred in Ifa. Dishonest actions bring spiritual consequences, while truthfulness aligns with divine will.",
    "karma": "The Yoruba concept of karma (Esan) teaches that good and bad actions return to a person in time.",
    "learn": "You can learn Ifa through a trained Babalawo or Iyanifa, studying the Odu Ifa and undergoing initiation if necessary.",
    "love": "Ifa reveals love compatibility through divination and helps people find partners aligned with their destiny.",
    "moon": "The Moon (Osupa) governs intuition, emotions, dreams, and spiritual insight.",
    "numerology": "Numerology in Ifa reveals hidden life patterns and spiritual insights through numbers.",
    "obatala": "Obatala is the Orisa of purity, and creation. He is regarded as the sculptor of human beings and the father of all Orisa.",
    "odu ifa": "Odu Ifa are the sacred scriptures of Ifa. There are 256 Odu, each containing verses, proverbs, and spiritual guidance for different aspects of life.",
    "offerings": "Offerings are gifts given to Orisa, ancestors, and spirits to seek favor, blessings, and protection.",
    "odu Ifa": "Odu Ifa are the sacred scriptures of Ifa, containing the wisdom and guidance of Orunmila.",
    "ogun": "Ogun is the Orisa of iron, war, technology, and perseverance. He is the spirit of progress, cutting through obstacles and ensuring success through hard work.",
    "olodumare": "Olodumare is the Supreme Creator in Yoruba spirituality, the source of all existence, and the ultimate force behind destiny.",
    "omens": "Omens are signs from nature, dreams, or random events that provide spiritual messages.",
    "oogun": "Charms are spiritual objects infused with energy to bring protection, luck, or influence events.",
    "opele": "Opele is a divination chain used by Babalawos to quickly cast and interpret messages from Ifa.",
    "ori": "Ori is one's spiritual consciousness and destiny. In Ifa, connecting with one's Ori is essential for success and fulfillment.",
    "orisa": "Everyone has a guardian Orisa (Orisa Ori) that influences their life path. A Babalawo can help determine one's guardian Orisa.",
    "orunmila": "Orunmila is the deity of wisdom, knowledge, and divination. He is the custodian of Ifa and the guide for humanity in understanding fate and destiny.",
    "oshun": "Oshun is the Orisa of love, beauty, fertility, and prosperity. She rules over freshwaters and rivers, healing the sick and bringing abundance.",
    "oya": "Oya is the Orisa of transformation, wind, and storms. She governs sudden change, spiritual rebirth, and the transition between life and death.",
    "planets": "In Ifa, celestial bodies influence human life. Each planet carries spiritual energy that affects destiny.",
    "prayers": "Prayers (Iwure) are spoken words of power used to invoke divine assistance and guidance from the Orisa and ancestors.",
    "predict": "Ifa does not predict the future in absolute terms but provides insight into possible outcomes and solutions.",
    "priest": "A Babalawo is a high priest of Ifa who is trained in divination, ritual work, and spiritual guidance.",
    "reincarnation": "Reincarnation (Atunwa) is the belief that souls return in a new body to complete their destiny and correct past mistakes.",
    "rituals": "Rituals in Ifa include prayers, sacrifices, offerings, and ceremonies performed to maintain spiritual balance.",
    "sacred elements": "The elements—fire, water, earth, and air—are important in Ifa as they represent different aspects of life and spiritual balance.",
    "sacrifice": "Sacrifices (Ebo) depend on the Odu revealed and the guidance of the Babalawo. They help balance energies and remove obstacles.",
    "sango": "Sango is the Orisa of thunder, lightning, and justice. A powerful warrior and former king, he represents strength, courage, and divine judgment.",
    "spirits": "Spirits can be protective or harmful. Ifa rituals help to control and appease them.",
    "spirit world": "The spirit world (Orun) is the realm of ancestors, Orisa, and divine beings who guide and influence life on Earth.",
    "spirituality": "Ifa spirituality is based on balance, wisdom, and alignment with divine forces through character, sacrifice, and knowledge.",
    "sun": "The Sun (Orun) symbolizes enlightenment, strength, leadership, and divine purpose.",
    "taboos": "Taboos (Eewo) are spiritual prohibitions revealed through Ifa divination. Avoiding them ensures alignment with one's destiny.",
     "wealth": "Ifa teaches that wealth (Aje) is not just money, but good health, wisdom, and strong relationships.",
    "witchcraft": "In Ifa, witchcraft (Aje) can be used for both positive and negative purposes. Good witches (Eleye) use their power for healing and protection.",
    "yemoja": "Yemoja is the mother of all Orisa, the goddess of the ocean, and protector of children. She represents nurturing, wisdom, and the waters of life.",

};
