const ifaKnowledgeBase = {
    "ifa": "Ifa is the sacred divination system of the Yoruba people, providing wisdom through Odu Ifa. It is the foundation of Yoruba spirituality and philosophy.",
    "destiny": "Destiny (Ori) is the divine path chosen before birth. In Ifa, it is believed that one must align with their Ori through wisdom, sacrifice (Ebo), and righteous living (Iwa Pele).",
    "orunmila": "Orunmila is the deity of wisdom, knowledge, and divination. He is the custodian of Ifa and the guide for humanity in understanding fate and destiny.",
    "eshu": "Esu is the divine messenger and trickster. He governs communication, crossroads, and choices. Without Esu, no prayers or sacrifices can reach the Orisa.",
    "ogun": "Ogun is the Orisa of iron, war, technology, and perseverance. He is the spirit of progress, cutting through obstacles and ensuring success through hard work.",
    "oshun": "Oshun is the Orisa of love, beauty, fertility, and prosperity. She rules over freshwaters and rivers, healing the sick and bringing abundance.",
    "sango": "Sango is the Orisa of thunder, lightning, and justice. A powerful warrior and former king, he represents strength, courage, and divine judgment.",
    "oya": "Oya is the Orisa of transformation, wind, and storms. She governs sudden change, spiritual rebirth, and the transition between life and death.",
    "yemoja": "Yemoja is the mother of all Orisa, the goddess of the ocean, and protector of children. She represents nurturing, wisdom, and the waters of life.",
    "olodumare": "Olodumare is the Supreme Creator in Yoruba spirituality, the source of all existence, and the ultimate force behind destiny.",
    "ori": "Ori is one's spiritual consciousness and destiny. In Ifa, connecting with one's Ori is essential for success and fulfillment.",
    "egungun": "Egungun represents the spirits of the ancestors. They are honored through rituals and ceremonies for protection, wisdom, and blessings.",
    "babalawo": "A Babalawo is a high priest of Ifa, trained in divination, spiritual guidance, and healing through the Odu Ifa.",
    "iyanifa": "Iyanifa is a female Ifa priest, trained in divination, spiritual guidance, and healing.",
    "odu ifa": "Odu Ifa are the sacred scriptures of Ifa. There are 256 Odu, each containing verses, proverbs, and spiritual guidance for different aspects of life.",
    "divination": "Divination in Ifa is performed using sacred palm nuts (Ikin Ifa) or the Opele chain to reveal divine messages through Odu Ifa.",
    "opele": "Opele is a divination chain used by Babalawos to quickly cast and interpret messages from Ifa.",
    "ebo": "Ebo is a ritual offering or sacrifice performed to correct spiritual imbalances, remove obstacles, and attract blessings.",
    "iwure": "Iwure is a prayer or blessing in Ifa, invoking divine favor and positive energy.",
    "isefa": "Isefa is the first step in Ifa initiation, where a person receives their first Ifa reading and learns about their spiritual path.",
    "itefa": "Itefa is the full initiation into Ifa, where an individual learns their Odu Ifa and becomes deeply connected with Ifa wisdom.",
    "taboos": "Taboos (Eewo) are spiritual prohibitions revealed through Ifa divination. Avoiding them ensures alignment with one's destiny.",
    "spirituality": "Ifa spirituality is based on balance, wisdom, and alignment with divine forces through character, sacrifice, and knowledge.",
    "numerology": "Numerology in Ifa reveals hidden life patterns and spiritual insights through numbers.",
    "planets": "In Ifa, celestial bodies influence human life. Each planet carries spiritual energy that affects destiny.",
    "sun": "The Sun (Orun) symbolizes enlightenment, strength, leadership, and divine purpose.",
    "moon": "The Moon (Osupa) governs intuition, emotions, dreams, and spiritual insight.",
    "earth": "The Earth (Aye) is the physical realm where humans live, and it is governed by spirits and ancestors.",
    "reincarnation": "Reincarnation (Atunwa) is the belief that souls return in a new body to complete their destiny and correct past mistakes.",
    "rituals": "Rituals in Ifa include prayers, sacrifices, offerings, and ceremonies performed to maintain spiritual balance.",
    "initiation": "Initiation (Itelodu) is the sacred process of being introduced into Ifa, receiving one's Odu, and learning one's spiritual mission.",
    "sacred elements": "The elements—fire, water, earth, and air—are important in Ifa as they represent different aspects of life and spiritual balance.",
    "spirit world": "The spirit world (Orun) is the realm of ancestors, Orisa, and divine beings who guide and influence life on Earth.",
    "offerings": "Offerings (Adimu) are gifts given to Orisa, ancestors, and spirits to seek favor, blessings, and protection.",
    "prayers": "Prayers (Adura) are spoken words of power used to invoke divine assistance and guidance from the Orisa and ancestors.",
    "sacred herbs": "Ifa uses herbs for healing, cleansing, and protection. Some powerful herbs include Ewe Ire, Ewe Ogbo, and Ewe Eyin.",
    "witchcraft": "In Ifa, witchcraft (Aje) can be used for both positive and negative purposes. Good witches (Aje Eleye) use their power for healing and protection.",
    "charms": "Charms (Ase) are spiritual objects infused with energy to bring protection, luck, or influence events.",
    "evil eye": "The evil eye (Ofo) is negative energy or jealousy sent by others. Ifa provides spiritual protection against it.",
    "dreams": "Dreams (Ala) are messages from the spirit world. Ifa teaches how to interpret dreams to understand hidden meanings.",
    "spirits": "Spirits can be protective or harmful. Ifa rituals help to control and appease them.",
    "cleansing": "Ifa recommends spiritual baths, prayers, and herbs to cleanse one's aura from negative energy.",
    "wealth": "Ifa teaches that wealth (Owo) is not just money, but good health, wisdom, and strong relationships.",
    "love": "Ifa reveals love compatibility through divination and helps people find partners aligned with their destiny.",
    "health": "In Ifa, health (Ilera) is connected to spiritual balance. Illness may be caused by spiritual imbalances and can be treated with rituals, herbs, and prayers.",
    "healing": "Healing in Ifa involves spiritual and physical remedies, including herbs, divination, and offerings to the Orisa.",
    "justice": "Justice (Ododo) is sacred in Ifa. Dishonest actions bring spiritual consequences, while truthfulness aligns with divine will.",
    "karma": "The Yoruba concept of karma (Esan) teaches that good and bad actions return to a person in time.",
    "Orisa": "Everyone has a guardian Orisa (Orisa Ori) that influences their life path. A Babalawo can help determine one's guardian Orisa.",
    "incantations": "Incantations (Ofa) are powerful spoken words used in Ifa rituals to invoke spiritual forces.",
    "omens": "Omens (Ibo) are signs from nature, dreams, or random events that provide spiritual messages.",
    "consultation": "Ifa consultation is a spiritual process in which a trained diviner (Babalawo) communicates with the divine to provide guidance. Done using sacred tools such as the Opele chain or palm nuts to reveal messages from the Odu Ifa. Before an Ifa consultation, you should have a clear mind, be open to guidance, and approach the process with sincerity.",
    "babalawo": "A Babalawo is a high priest of Ifa who is trained in divination, ritual work, and spiritual guidance.",
    "odu Ifa": "Odu Ifa are the sacred scriptures of Ifa, containing the wisdom and guidance of Orunmila.",
    "sacrifice": "Sacrifices (Ebo) depend on the Odu revealed and the guidance of the Babalawo. They help balance energies and remove obstacles.",
    "who can consult Ifa": "Anyone seeking guidance, whether Yoruba or not, can consult Ifa for wisdom and direction.",
    "can women become Ifa priests": "Yes, women can become Iyanifas, who are female priests trained in Ifa wisdom and divination.",
    "predict the future": "Ifa does not predict the future in absolute terms but provides insight into possible outcomes and solutions.",
    "learn": "You can learn Ifa through a trained Babalawo or Iyanifa, studying the Odu Ifa and undergoing initiation if necessary."
};
