       // Numerology meanings based on single-digit life path numbers
        const numerologyMeanings = {
            1: "Linked to new beginnings, leadership, and creativity, you are ambitious and excel when taking the initiative. Make it a priority to start new ventures. Expect frequent travels. Pay special attention to your head. Engage in prayers with water and use it to rinse your head while on the floor, ensuring that your head does not make contact with the ground or any object. Governed by the Sun, this energy embodies confidence, vitality, and self-expression, resonating with Aries' bold and determined nature.",

            2: "Represents balance, duality, and transformation. You are diplomatic and strive for harmony in relationships. Be open to receiving blessings. Start small, and with time, it will flourish. Governed by the Moon, this energy is deeply connected to emotions and intuition, aligning with Cancer’s nurturing essence. Ibeji, an Orisha symbolizing twins, children, and joy, is associated with the sacred number 2. This number reflects Ibeji’s dual nature and the power of balance and harmony. Often depicted as two children, Ibeji represents the inseparable bond of twins and the joy of childhood. Additionally, the number 2 signifies life’s duality and the equilibrium between positive and negative forces",

            3: "Represents communication, adaptability, and growth. You have a natural gift for expression and inspire optimism in others. Prepare to welcome prosperity. Governed by Jupiter, this energy signifies expansion and inspiration, resonating with Sagittarius' adventurous nature.Elegua, also known as Eshu, is an Orisha associated with communication, trickery, and crossroads. Linked to the sacred number 3, this number symbolizes his ability to move between different realms and his trickster essence. It also represents the three roads that intersect at a crossroads, signifying his role as the guardian of paths and doors in this world.Elegua embodies the essence of ashé and is represented by the colors red and black or white and black, reflecting his dual and paradoxical nature. As the intermediary between the human and the divine, he serves as a childlike messenger between both worlds. His deep connection with Orunmila, the Orisha of divination, highlights his pivotal role—nothing can proceed without his consent. He is always honored first, as he opens the doors between worlds and clears the path for life's journey.",

            4: "Symbolizes stability, security, and structure. You are grounded and appreciate order in life. Maintain a low profile and avoid travel during this period. Governed by Saturn, this energy embodies discipline and responsibility, aligning with Capricorn's practical and strategic mindset. The number four represents completion and stability, reflected in the four fundamental elements—Earth, Air, Fire, and Water. It also signifies structure, order, and justice, as well as the four cardinal directions: East, West, North, and South. As a powerful number, it holds the potential to bring balance and harmony when embraced with intention.",

            5: "Represents freedom, exploration, and spiritual inquiry. You thrive in change and eagerly seek new possibilities. Expect frequent travel, but be mindful of challenges in your marriage, particularly regarding divorce. Governed by Mercury, this energy signifies quick thinking and adaptability, resonating with the inquisitive nature of Gemini and Virgo.Oshun, the Orisha of love, beauty, and abundance, is linked to the sacred number 5. This number reflects her sensual and generous spirit, as well as her deep connection to the flow of water and the natural world. It also symbolizes the five senses and the five fundamental elements of nature, embodying harmony, pleasure, and life’s ever-changing currents.",

            6: "Represents harmony, love, and nurturing. You are compassionate and strive to create a peaceful and loving home. This is a time for enjoyment, social gatherings, and celebrations. Governed by Venus, this energy embodies love and beauty, aligning with Taurus' stability and Libra's sense of balance.Sango, the Orisha of thunder, lightning, and justice, is associated with the sacred number 6. This number reflects his strength, authority, and deep connection to the natural elements. It also symbolizes the six aspects of Sango’s power, representing his dynamic and commanding presence in both the physical and spiritual realms",

            7: "Tied to analysis, wisdom, and introspection. You are analytical and seek a deeper understanding of life. Be careful of prison and poison. Say more of positive things because the spirits are waiting to listen to you. Ruled by Neptune. Represents intuition and mysticism. Linked to Pisces' spiritual depth. Ogun, the Orisha of iron, war and labor, is closely tied to the number 7. This number is revered, representing perfection and completeness. For Ogun, it captures his dual essence as both a fierce warrior and a skilled craftsman. The number 7 signifies his powerful influence, reflecting his dominant presence across both spiritual and physical realms. He is the owner of all technology and because this technology shares in his nature, it is almost always used first for war. As Elegba opens the roads, it is Ogún that clears the roads with his machete. He is recognised in the numbers 7 and the colors green and black.",

            8: "Indicates ambition, power, and material success. The number eight holds a special place due to its association with luck, wealth, and success. It is also linked to personal growth, success, and leadership. Number 8 likewise embodies the energy of karma. When number 8 shows up in auspicious ways, expect to receive what you have given. Don't keep your money with people for returns or investment. Ruled by Saturn. Reflects discipline and mastery. Often tied to Capricorn's drive for achievement. Obatala is an Orisha that represents purity, wisdom, and creativity. Obatala is associated with the sacred number 8. He is also the owner of all heads and the mind. Though it was Olorun who created the universe, it is Obatalá who is the creator of the world and humanity. Obatalá is the source of all that is pure, wise peaceful and compassionate. He has a warrior side though through which he enforces justice in the world. His color is white which is often accented with red, purple and other colors to represent his/her different paths. White is most appropriate for Obatalá as it contains all the colors of the rainbow yet is above them. Obatalá is also the only orisha that has both male and female paths",

            9: "Suggests humanitarianism, completion, and service. You are idealistic and seek to serve others. Avoid violent/conflict and take things easy to avoid disaster /destruction. Ruled by Mars. Represents passion and courage. Connected to Scorpio's transformative energy. Oya is an Orisha that represents winds, storms, and transformation. Oya is associated with the sacred number 9. The numbers reflect her power and influence, as well as her ability to create change and transformation. The number 9 represents the nine aspects of Oya's power and her connection to the nine realms of existence. Oyá is the ruler of the winds, the whirlwind and the gates of the cemetery. Her number is nine which recalls her title of Yansa or 'Mother of Nine' in which she rules over the egun or dead. She is also known for the colors of maroon, flowery patterns and nine different colors. She is a fierce warrior who rides to war with Shangó (sharing lightning and fire with him) and was once the wife of Ogún."
        };